### ISSUE TITLE
Dependencies in lib folder

### ISSUE THREAD

**Issue by tknobi** [nomve/Tuio.js#8]
Having dependencies committed in the lib folder is not a good solution in my opinion.

For example, users of my application have to load the lodash dependency twice.

**Comment by nomve** [comment]
In general, you need to know that the TUIO2 support is really basic and probably not really correct, and if there will be time invested into any work on this, it should not be to do this type of maintenance.

The reason they are there is because they were in the original library and I never bothered to clean them up.

Also check this https://github.com/nomve/Tuio.js/issues/3
